# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mychatbot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmychatbot.proto\x12\rsimplechatbot\"\x1d\n\x0bpredict_req\x12\x0e\n\x06input1\x18\x01 \x01(\t\"\x1f\n\x0cpredict_resp\x12\x0f\n\x07output1\x18\x01 \x01(\t2S\n\rsimplechatbot\x12\x42\n\x07predict\x12\x1a.simplechatbot.predict_req\x1a\x1b.simplechatbot.predict_respb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mychatbot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PREDICT_REQ']._serialized_start=34
  _globals['_PREDICT_REQ']._serialized_end=63
  _globals['_PREDICT_RESP']._serialized_start=65
  _globals['_PREDICT_RESP']._serialized_end=96
  _globals['_SIMPLECHATBOT']._serialized_start=98
  _globals['_SIMPLECHATBOT']._serialized_end=181
# @@protoc_insertion_point(module_scope)
